### ISSUE TITLE
LOGICA PROPOSICIONAL

### ISSUE THREAD

**Issue by QUET012** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-QUET012#3]
[LOGICA PROPOSICIONAL QUETZALLI GARCIA GARCIA 5.pdf](https://github.com/user-attachments/files/17514510/LOGICA.PROPOSICIONAL.QUETZALLI.GARCIA.GARCIA.5.pdf)

**Comment by AlynGomez12** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
